/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class createUserForm extends javax.swing.JInternalFrame {
    public String id;
    /**
     * Creates new form createUSerForm
     */
    public createUserForm() {
        initComponents();
       

    }
   public void fillFields(String name, String email, String username, String phone, String password) {
    fn.setText(name);
    em.setText(email);
    un.setText(username);
    ph.setText(phone);
    ps.setText(password);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        username1 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        username2 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        username4 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        ph = new javax.swing.JTextField();
        cpword = new javax.swing.JTextField();
        ps = new javax.swing.JTextField();
        username6 = new javax.swing.JLabel();
        username7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        utype = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username1.setBackground(new java.awt.Color(204, 204, 204));
        username1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username1.setForeground(new java.awt.Color(255, 255, 255));
        username1.setText("Confirm Password:");
        jPanel1.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        fn.setBackground(new java.awt.Color(204, 204, 204));
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 230, 30));

        em.setBackground(new java.awt.Color(204, 204, 204));
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        jPanel1.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 230, 30));

        username2.setBackground(new java.awt.Color(204, 204, 204));
        username2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username2.setForeground(new java.awt.Color(255, 255, 255));
        username2.setText("Full Name:");
        jPanel1.add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        username3.setBackground(new java.awt.Color(204, 204, 204));
        username3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username3.setForeground(new java.awt.Color(255, 255, 255));
        username3.setText("Email:");
        jPanel1.add(username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        username4.setBackground(new java.awt.Color(204, 204, 204));
        username4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username4.setForeground(new java.awt.Color(255, 255, 255));
        username4.setText("Password:");
        jPanel1.add(username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        un.setBackground(new java.awt.Color(204, 204, 204));
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        jPanel1.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 230, 30));

        ph.setBackground(new java.awt.Color(204, 204, 204));
        ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phActionPerformed(evt);
            }
        });
        jPanel1.add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 230, 30));

        cpword.setBackground(new java.awt.Color(204, 204, 204));
        cpword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpwordActionPerformed(evt);
            }
        });
        jPanel1.add(cpword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 230, 30));

        ps.setBackground(new java.awt.Color(204, 204, 204));
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });
        jPanel1.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 230, 30));

        username6.setBackground(new java.awt.Color(204, 204, 204));
        username6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username6.setForeground(new java.awt.Color(255, 255, 255));
        username6.setText("Username:");
        jPanel1.add(username6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        username7.setBackground(new java.awt.Color(204, 204, 204));
        username7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username7.setForeground(new java.awt.Color(255, 255, 255));
        username7.setText("Phone Number:");
        jPanel1.add(username7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("REGISTRATION");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 220, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 60));

        update.setBackground(new java.awt.Color(204, 204, 204));
        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("UPDATE USER");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 180, 40));

        utype.setBackground(new java.awt.Color(102, 102, 102));
        utype.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        utype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "STAFf" }));
        utype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utypeActionPerformed(evt);
            }
        });
        jPanel1.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 90, 40));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(51, 51, 51));
        add.setText("ADD USER");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 190, 40));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 530, 320));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed

    private void phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phActionPerformed

    private void cpwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpwordActionPerformed

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psActionPerformed

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered

    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited

    }//GEN-LAST:event_updateMouseExited

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       config.configclass conf = new config.configclass();
    
    // The 'WHERE u_id = ?' uses your hidden 'id' variable
    String sql = "UPDATE users SET u_fname=?, u_email=?, u_username=?, u_phone=?, u_password=?, u_type=? WHERE u_id=?";

    if (conf.insertData(sql, fn.getText(), em.getText(), un.getText(), 
                        ph.getText(), ps.getText(), utype.getSelectedItem().toString(), id) == 1) {
        
        JOptionPane.showMessageDialog(null, "User Updated!");
        this.dispose();
    }
    }//GEN-LAST:event_updateActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
    config.configclass conf = new config.configclass();
    
    // Check if fields are empty first
    if(fn.getText().isEmpty() || em.getText().isEmpty() || un.getText().isEmpty() || ps.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields are required!");
    } else {
        // Change 'Active' to 'Pending' here so they don't go straight to Active
        String sql = "INSERT INTO users (u_fname, u_email, u_username, u_phone, u_password, u_type, u_status) "
                   + "VALUES (?, ?, ?, ?, ?, ?, 'Pending')"; 

        int result = conf.insertData(sql, fn.getText(), em.getText(), un.getText(), 
                                     ph.getText(), ps.getText(), utype.getSelectedItem().toString());

        if(result == 1) {
            JOptionPane.showMessageDialog(null, "User Registered as Pending!");
            this.dispose(); // Close the pop-up after adding
        }
    }
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseExited

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void utypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add;
    public javax.swing.JTextField cpword;
    public javax.swing.JTextField em;
    public javax.swing.JTextField fn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTextField ph;
    public javax.swing.JTextField ps;
    public javax.swing.JTextField un;
    public javax.swing.JButton update;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username4;
    private javax.swing.JLabel username6;
    private javax.swing.JLabel username7;
    public javax.swing.JComboBox<String> utype;
    // End of variables declaration//GEN-END:variables



   
}

