/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class editProfileForm extends javax.swing.JFrame {
    public String id;
    /**
     * Creates new form editProfileForm
     */
    public editProfileForm() {
        initComponents();
    }
    Color navcolor = new Color (102,102,102);
     Color headcolor = new Color (51,51,51);
     Color bodycolor = new Color (153,153,153);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fullname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        p_email = new javax.swing.JTextField();
        p_name = new javax.swing.JTextField();
        p_id = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        confirmEdit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        manageUser1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        members = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullname.setBackground(new java.awt.Color(204, 204, 204));
        fullname.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        fullname.setForeground(new java.awt.Color(204, 204, 204));
        fullname.setText("Full name: ");
        jPanel2.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 30));

        email.setBackground(new java.awt.Color(204, 204, 204));
        email.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setText("Email: ");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, 30));

        ID.setBackground(new java.awt.Color(204, 204, 204));
        ID.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        ID.setForeground(new java.awt.Color(204, 204, 204));
        ID.setText("User ID: ");
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 30));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 100));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 160, 140));

        p_email.setBackground(new java.awt.Color(102, 102, 102));
        p_email.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        p_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(p_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 200, 30));

        p_name.setBackground(new java.awt.Color(102, 102, 102));
        p_name.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        p_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 200, 30));

        p_id.setEditable(false);
        p_id.setBackground(new java.awt.Color(102, 102, 102));
        p_id.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        p_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 200, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 190));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmEdit.setBackground(new java.awt.Color(204, 204, 204));
        confirmEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmEditMouseExited(evt);
            }
        });
        confirmEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/confirmedit.png"))); // NOI18N
        confirmEdit.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 110));

        username1.setBackground(new java.awt.Color(0, 0, 0));
        username1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username1.setText("CONFIRM EDIT");
        confirmEdit.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

        jPanel3.add(confirmEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 170, 150));

        manageUser1.setBackground(new java.awt.Color(204, 204, 204));
        manageUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageUser1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageUser1MouseExited(evt);
            }
        });
        manageUser1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reports.png"))); // NOI18N
        manageUser1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 110));

        username2.setBackground(new java.awt.Color(0, 0, 0));
        username2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username2.setText("REPORTS");
        manageUser1.add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 20));

        jPanel3.add(manageUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 170, 150));

        members.setBackground(new java.awt.Color(204, 204, 204));
        members.setPreferredSize(new java.awt.Dimension(160, 160));
        members.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                membersMouseExited(evt);
            }
        });
        members.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        members.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 110));

        username3.setBackground(new java.awt.Color(0, 0, 0));
        username3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username3.setText("LOG OUT");
        members.add(username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

        jPanel3.add(members, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 690, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmEditMouseClicked
    String sql = "UPDATE users SET u_fname = ?, u_email = ? WHERE u_id = ?";
    
    try {
        config.configclass conf = new config.configclass();
        java.sql.Connection conn = conf.connectDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        pst.setString(1, p_name.getText());
        pst.setString(2, p_email.getText());
        pst.setString(3, p_id.getText());
        
        int rowsUpdated = pst.executeUpdate();
        
        if (rowsUpdated > 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Successfully Updated!");
            
            // --- REFRESH LOGIC STARTS HERE ---
            // If you are using a DesktopPane or a specific Panel to hold these pages:
            // You can call the display method of the parent if it's accessible.
            
            this.dispose(); // Closes the edit window
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_confirmEditMouseClicked

    private void confirmEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmEditMouseEntered
        confirmEdit.setBackground(navcolor);
    }//GEN-LAST:event_confirmEditMouseEntered

    private void confirmEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmEditMouseExited
        confirmEdit.setBackground(headcolor);
    }//GEN-LAST:event_confirmEditMouseExited

    private void manageUser1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUser1MouseEntered
        confirmEdit.setBackground(navcolor);
    }//GEN-LAST:event_manageUser1MouseEntered

    private void manageUser1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUser1MouseExited
        confirmEdit.setBackground(headcolor);
    }//GEN-LAST:event_manageUser1MouseExited

    private void membersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseClicked

    }//GEN-LAST:event_membersMouseClicked

    private void membersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseEntered
        members.setBackground(navcolor);
    }//GEN-LAST:event_membersMouseEntered

    private void membersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseExited
        members.setBackground(headcolor);
    }//GEN-LAST:event_membersMouseExited
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JPanel confirmEdit;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel manageUser1;
    private javax.swing.JPanel members;
    public javax.swing.JTextField p_email;
    public javax.swing.JTextField p_id;
    public javax.swing.JTextField p_name;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    // End of variables declaration//GEN-END:variables
}
