package internalPages;


import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class membersForm extends javax.swing.JFrame {

    public String id;
   
    public membersForm() {
        initComponents();
        
    }
    Color navcolor = new Color (102,102,102);
     Color headcolor = new Color (51,51,51);
     Color bodycolor = new Color (153,153,153);
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memberform = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        wrong = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        add = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        gender = new javax.swing.JLabel();
        Status = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        memberform.setBackground(new java.awt.Color(204, 204, 204));
        memberform.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        memberform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MEMBERS FORM");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 20));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 40));

        wrong.setBackground(new java.awt.Color(51, 51, 51));
        wrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wrongMouseClicked(evt);
            }
        });
        wrong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wrong.png"))); // NOI18N
        wrong.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 40));

        jPanel4.add(wrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 70, 60));

        memberform.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(102, 102, 102));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADD");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 150, 30));

        update.setBackground(new java.awt.Color(102, 102, 102));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("UPDATE");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        update.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 150, -1));

        status.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        status.setText("Status:");
        jPanel3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 30));

        firstname.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        firstname.setText("First Name:");
        jPanel3.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, 30));

        lastname.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lastname.setText("Last Name:");
        jPanel3.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 30));

        fname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fname.setOpaque(false);
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel3.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 200, 30));

        lname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lname.setOpaque(false);
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel3.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 200, 30));

        male.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        male.setText("MALE");
        jPanel3.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 100, 30));

        female.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        female.setText("FEMALE");
        jPanel3.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 100, 30));

        gender.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        gender.setText("Gender:");
        jPanel3.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 30));

        Status.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Maried" }));
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });
        jPanel3.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 200, 30));

        memberform.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 380));

        getContentPane().add(memberform, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(bodycolor);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(navcolor);
    }//GEN-LAST:event_addMouseExited

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        update.setBackground(bodycolor);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        update.setBackground(navcolor);
    }//GEN-LAST:event_updateMouseExited

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusActionPerformed

    private void wrongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wrongMouseClicked
   // 1. Close this popup form
    this.dispose();

    // 2. Find the dashboard window you are already in
    javax.swing.JFrame topFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    
    try {
        // 3. Access the blue area (maindesktop)
        java.lang.reflect.Field field = topFrame.getClass().getDeclaredField("maindesktop");
        field.setAccessible(true);
        javax.swing.JDesktopPane desktop = (javax.swing.JDesktopPane) field.get(topFrame);
        
        // 4. Clear the screen and load the MEMBERS table
        desktop.removeAll();
        member m = new member(); // This loads your table page
        desktop.add(m).setVisible(true);
        
        // 5. Refresh the screen
        desktop.revalidate();
        desktop.repaint();
        
    } catch (Exception e) {
        // This part only runs if the first part fails
        System.out.println("Error returning to Members: " + e.getMessage());
    }
    }//GEN-LAST:event_wrongMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
       
    String fname = this.fname.getText(); 
    String lname = this.lname.getText();
    String gen = male.isSelected() ? "Male" : "Female";
    String stat = Status.getSelectedItem().toString();

    
    String sql = "INSERT INTO members (m_fname, m_lname, m_gender, m_status) VALUES (?, ?, ?, ?)";

    try {
        config.configclass conf = new config.configclass();
        java.sql.Connection conn = conf.connectDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

      
        pst.setString(1, fname); 
        pst.setString(2, lname);
        pst.setString(3, gen);
        pst.setString(4, stat);

        pst.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(null, "Successfully Added!");

       
        this.dispose(); 
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_addMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
    
    String f_name = fname.getText();
    String l_name = lname.getText();
    String gen = male.isSelected() ? "Male" : "Female";
    String stat = Status.getSelectedItem().toString();

   
    String sql = "UPDATE members SET m_fname = ?, m_lname = ?, m_gender = ?, m_status = ? WHERE m_id = ?";

    try {
        
        config.configclass conf = new config.configclass();
        java.sql.Connection conn = conf.connectDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

      
        pst.setString(1, f_name);
        pst.setString(2, l_name);
        pst.setString(3, gen);
        pst.setString(4, stat);
        pst.setString(5, id); 

        pst.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(null, "Successfully Updated!");
        
        
        this.dispose();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_updateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(membersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(membersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(membersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(membersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new membersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Status;
    public javax.swing.JPanel add;
    public javax.swing.JRadioButton female;
    private javax.swing.JLabel firstname;
    public javax.swing.JTextField fname;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lastname;
    public javax.swing.JTextField lname;
    public javax.swing.JRadioButton male;
    private javax.swing.JPanel memberform;
    private javax.swing.JLabel status;
    public javax.swing.JPanel update;
    private javax.swing.JPanel wrong;
    // End of variables declaration//GEN-END:variables


}
