/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class Payments extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form managePayments
     */
    public Payments() {
       initComponents();
       displayData();
       paymentsForm pf = new paymentsForm();
       pf.setVisible(true);
       // Automatically fill the Member ID field
   String id = config.Session.getInstance().getSelectedMemberID();
if (id != null) {
    search3.setText(id); 
    }
       this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
      BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
      bi.setNorthPane(null);
    }
    
    public void displayData() {
    config.configclass cc = new config.configclass();
    // This fetches the latest info from your payments table
    cc.displayData("SELECT p_id as 'ID', p_member_id as 'Member ID', "
                 + "p_amount as 'Amount', p_category as 'Category', "
                 + "p_date as 'Date', p_status as 'Status' FROM payments", payment_table);

    }
    
    private String getSelectedPaymentId() {
        int rowIndex = payment_table.getSelectedRow();
        if (rowIndex < 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select a record from the table first!");
            return null;
        }
        return payment_table.getModel().getValueAt(rowIndex, 0).toString();
    }
    Color navcolor = new Color (102,102,102);
     Color headcolor = new Color (51,51,51);
     Color bodycolor = new Color (153,153,153);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentspanel = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        payment_table = new javax.swing.JTable();
        search3 = new javax.swing.JTextField();
        searchUser = new javax.swing.JPanel();
        search = new javax.swing.JLabel();
        refresh = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paymentspanel.setBackground(new java.awt.Color(204, 204, 204));
        paymentspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PAYMENTS");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel14.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 20));

        jPanel15.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 40));

        paymentspanel.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        jPanel16.setBackground(new java.awt.Color(153, 153, 153));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        payment_table.setAutoCreateRowSorter(true);
        payment_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        payment_table.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        payment_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "member ID", "ammount", "category", "status", "date", "Status"
            }
        ));
        payment_table.setSelectionBackground(new java.awt.Color(102, 102, 102));
        payment_table.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane4.setViewportView(payment_table);

        jPanel16.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 700, 280));

        search3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        search3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search3.setOpaque(false);
        search3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search3MouseClicked(evt);
            }
        });
        search3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search3ActionPerformed(evt);
            }
        });
        jPanel16.add(search3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 200, 30));

        searchUser.setBackground(new java.awt.Color(102, 102, 102));
        searchUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchUserMouseExited(evt);
            }
        });
        searchUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setBackground(new java.awt.Color(51, 51, 51));
        search.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search.setText("SEARCH");
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchUser.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel16.add(searchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 80, 30));

        refresh.setBackground(new java.awt.Color(153, 153, 153));
        refresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshMouseExited(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N

        javax.swing.GroupLayout refreshLayout = new javax.swing.GroupLayout(refresh);
        refresh.setLayout(refreshLayout);
        refreshLayout.setHorizontalGroup(
            refreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refreshLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        refreshLayout.setVerticalGroup(
            refreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refreshLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel16.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 30, 30));

        update.setBackground(new java.awt.Color(102, 102, 102));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("UPDATE");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        update.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel16.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 80, 30));

        delete.setBackground(new java.awt.Color(102, 102, 102));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DELETE");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        delete.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel16.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 80, 30));

        add.setBackground(new java.awt.Color(102, 102, 102));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADD");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel16.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        paymentspanel.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 380));

        getContentPane().add(paymentspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_search3MouseClicked

    private void search3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search3ActionPerformed

    }//GEN-LAST:event_search3ActionPerformed

    private void searchUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchUserMouseClicked
        config.configclass conf = new config.configclass();
    
    // 1. Get the text from your search field (search3 in your code)
    String txt = search3.getText();
    
    // 2. Create the SQL query using your database column names
    // We use LIKE and % symbols to find partial matches
    String query = "SELECT * FROM payments WHERE m_id LIKE '%" + txt + "%' "
                 + "OR p_member_id LIKE '%" + txt + "%' "
                 + "OR p_status LIKE '%" + txt + "%' "
                 + "OR p_category LIKE '%" + txt + "%'";

    // 3. Update the table with the filtered results
    conf.displayData(query, payment_table);
    }//GEN-LAST:event_searchUserMouseClicked

    private void searchUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchUserMouseEntered
        searchUser.setBackground(bodycolor);
    }//GEN-LAST:event_searchUserMouseEntered

    private void searchUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchUserMouseExited
        searchUser.setBackground(navcolor);
    }//GEN-LAST:event_searchUserMouseExited

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
       // 1. Clear the text field using the CORRECT name from your search logic
    search3.setText(""); 
    
    // 2. Reload the full table
    displayData(); 
    
    System.out.println("Table Refreshed");
    }//GEN-LAST:event_refreshMouseClicked

    private void refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseEntered
        refresh.setBackground(bodycolor);
    }//GEN-LAST:event_refreshMouseEntered

    private void refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseExited
        refresh.setBackground(navcolor);
    }//GEN-LAST:event_refreshMouseExited

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        int rowIndex = payment_table.getSelectedRow(); 

    if (rowIndex < 0) {
        javax.swing.JOptionPane.showMessageDialog(null, "Please select an item to update!");
    } else {
        try {
            TableModel model = payment_table.getModel();
            paymentsForm pf = new paymentsForm();

            // IMPORTANT: Store the Primary Key (m_id) in the 'Name' property for the WHERE clause
            pf.m_id.setName(model.getValueAt(rowIndex, 0).toString());

            // Transfer data from table to Form fields
            pf.m_id.setText(model.getValueAt(rowIndex, 1).toString());      // Member ID
            pf.ammount1.setText(model.getValueAt(rowIndex, 2).toString());  // Amount
            pf.jComboBox1.setSelectedItem(model.getValueAt(rowIndex, 3).toString()); // Category
            pf.ammount.setText(model.getValueAt(rowIndex, 5).toString());   // Cashier name

            // Change UI to Update Mode
            pf.jLabel1.setText("UPDATE PAYMENT");
            pf.jLabel7.setText("UPDATE");

            // Display the form inside the DesktopPane
            this.getDesktopPane().add(pf);
            pf.setVisible(true);

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        update.setBackground(bodycolor);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        update.setBackground(navcolor);
    }//GEN-LAST:event_updateMouseExited

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
      int rowIndex = payment_table.getSelectedRow();
    
    if (rowIndex < 0) {
        javax.swing.JOptionPane.showMessageDialog(null, "Please select a row to delete!");
    } else {
        TableModel model = payment_table.getModel();
        // Column 0 is the ID column in your table
        String id = model.getValueAt(rowIndex, 0).toString();
        
        int confirm = javax.swing.JOptionPane.showConfirmDialog(null, 
                "Are you sure you want to delete Payment ID: " + id + "?", "Warning", 
                javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            config.configclass conf = new config.configclass();
            // IMPORTANT: Changed 'm_id' to 'p_id' to match your database
            String query = "DELETE FROM payments WHERE p_id = '" + id + "'";
            conf.deleteData(query);
            displayData(); // This refreshes the table
        }
    }
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        delete.setBackground(bodycolor);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        delete.setBackground(navcolor);
    }//GEN-LAST:event_deleteMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
  paymentsForm pf = new paymentsForm();
    this.getDesktopPane().add(pf); 
    pf.setVisible(true);
    
    // 1. Get the ID from the session
    String id = config.Session.getInstance().getSelectedMemberID();
    
    // 2. Pass it to the text field in the popup form
    if (id != null) {
        pf.m_id.setText(id); 
    }
    
    pf.jLabel1.setText("CONFIRM PAYMENT"); 
    pf.setSize(370, 560); 
    pf.setLocation(200, 20);
    
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(bodycolor);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(navcolor);
    }//GEN-LAST:event_addMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel add;
    public javax.swing.JPanel delete;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable payment_table;
    public javax.swing.JPanel paymentspanel;
    private javax.swing.JPanel refresh;
    private javax.swing.JLabel search;
    private javax.swing.JTextField search3;
    private javax.swing.JPanel searchUser;
    public javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
