/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;

/**
 *
 * @author USER42
 */
public class userprofile extends javax.swing.JInternalFrame {

    /**
     * Creates new form accountsettings
     */
    public userprofile() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);

    // Auto center when opened
    javax.swing.SwingUtilities.invokeLater(() -> {
        if (getParent() != null) {
            int x = (getParent().getWidth() - getWidth()) / 2;
            int y = (getParent().getHeight() - getHeight()) / 2;
            setLocation(x, y);
        }
    });
        
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }
    Color navcolor = new Color (102,102,102);
     Color headcolor = new Color (51,51,51);
     Color bodycolor = new Color (153,153,153);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fullname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        p_email = new javax.swing.JLabel();
        p_name = new javax.swing.JLabel();
        p_id = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        editProfile = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        reports = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullname.setBackground(new java.awt.Color(204, 204, 204));
        fullname.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        fullname.setForeground(new java.awt.Color(204, 204, 204));
        fullname.setText("Full name: ");
        jPanel2.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 30));

        email.setBackground(new java.awt.Color(204, 204, 204));
        email.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setText("Email: ");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, 30));

        ID.setBackground(new java.awt.Color(204, 204, 204));
        ID.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        ID.setForeground(new java.awt.Color(204, 204, 204));
        ID.setText("User ID: ");
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 30));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 100));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 160, 140));

        p_email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        p_email.setForeground(new java.awt.Color(204, 204, 204));
        p_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(p_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 180, 30));

        p_name.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        p_name.setForeground(new java.awt.Color(204, 204, 204));
        p_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 180, 30));

        p_id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        p_id.setForeground(new java.awt.Color(204, 204, 204));
        p_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 190));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editProfile.setBackground(new java.awt.Color(204, 204, 204));
        editProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProfileMouseExited(evt);
            }
        });
        editProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit profile.png"))); // NOI18N
        editProfile.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 110));

        username1.setBackground(new java.awt.Color(0, 0, 0));
        username1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username1.setText("EDIT PROFILE");
        editProfile.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

        jPanel3.add(editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 170, 150));

        reports.setBackground(new java.awt.Color(204, 204, 204));
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        reports.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reports.png"))); // NOI18N
        reports.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 110));

        username2.setBackground(new java.awt.Color(0, 0, 0));
        username2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username2.setText("REPORTS");
        reports.add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 20));

        jPanel3.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 170, 150));

        logout.setBackground(new java.awt.Color(204, 204, 204));
        logout.setPreferredSize(new java.awt.Dimension(160, 160));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logout.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 110));

        username3.setBackground(new java.awt.Color(0, 0, 0));
        username3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username3.setText("LOG OUT");
        logout.add(username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

        jPanel3.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 690, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseEntered
        editProfile.setBackground(navcolor);
    }//GEN-LAST:event_editProfileMouseEntered

    private void editProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseExited
        editProfile.setBackground(headcolor);
    }//GEN-LAST:event_editProfileMouseExited

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
        reports.setBackground(navcolor);
    }//GEN-LAST:event_reportsMouseEntered

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
        reports.setBackground(headcolor);
    }//GEN-LAST:event_reportsMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
    int a = javax.swing.JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout", javax.swing.JOptionPane.YES_NO_OPTION);
    
if (a == javax.swing.JOptionPane.YES_OPTION) {
    // 1. Get the current window and close it
    java.awt.Window mainFrame = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (mainFrame != null) {
        mainFrame.dispose();
    }
    
    // 2. Open the LANDING PAGE instead of login
    try {
        // We change "logIn" to "landingpage" to match your file name
        Class<?> landingClass = Class.forName("landingpage"); 
        javax.swing.JFrame landingPage = (javax.swing.JFrame) landingClass.newInstance();
        landingPage.setVisible(true);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error opening landing page: " + e.getMessage());
    }
}
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(navcolor);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(headcolor);
    }//GEN-LAST:event_logoutMouseExited

    private void editProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseClicked
  editProfileForm epf = new editProfileForm();
    
    // We pull text from p_id, p_name, and p_email because 
    // these contain the RAW data (e.g., "1") without the "User ID:" prefix.
    epf.p_id.setText(p_id.getText()); 
    epf.p_name.setText(p_name.getText()); 
    epf.p_email.setText(p_email.getText());
    
    epf.setVisible(true);
     epf.setLocationRelativeTo(null); 
    }//GEN-LAST:event_editProfileMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ID;
    private javax.swing.JPanel editProfile;
    public javax.swing.JLabel email;
    public javax.swing.JLabel fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel logout;
    public javax.swing.JLabel p_email;
    public javax.swing.JLabel p_id;
    public javax.swing.JLabel p_name;
    private javax.swing.JPanel reports;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    // End of variables declaration//GEN-END:variables
}
