/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
    import java.awt.Color;
    import internalPages.*;
    import internalPages.dashBoardPage;
    import config.Session;
    
/**
 *
 * @author Admin
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboadrd
     */
    public dashboard() {
        
   initComponents(); 
    config.Session sess = config.Session.getInstance();
    
  
    if (sess.getType() != null && sess.getType().equalsIgnoreCase("STAFF")) {
        
              
        
    }
        
    }
     Color navcolor = new Color (102,102,102);
     Color headcolor = new Color (51,51,51);
     Color bodycolor = new Color (153,153,153);
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        dashpane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        account = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        payments = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        active = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        membershipPlans = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        dashlogout = new javax.swing.JButton();
        maindesktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        navbar.setBackground(new java.awt.Color(102, 102, 102));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashpane.setBackground(new java.awt.Color(102, 102, 102));
        dashpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashpaneMouseExited(evt);
            }
        });
        dashpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("    DASHBOARD");
        dashpane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 170, 40));

        navbar.add(dashpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, 40));

        account.setBackground(new java.awt.Color(102, 102, 102));
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountMouseExited(evt);
            }
        });
        account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ACCOUNT");
        account.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        navbar.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 170, 40));

        payments.setBackground(new java.awt.Color(102, 102, 102));
        payments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paymentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paymentsMouseExited(evt);
            }
        });
        payments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PAYMENTS");
        payments.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        navbar.add(payments, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 170, 40));

        active.setBackground(new java.awt.Color(102, 102, 102));
        active.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                activeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                activeMouseExited(evt);
            }
        });
        active.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ACTIVE");
        active.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        navbar.add(active, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 170, 40));

        membershipPlans.setBackground(new java.awt.Color(102, 102, 102));
        membershipPlans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membershipPlansMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membershipPlansMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                membershipPlansMouseExited(evt);
            }
        });
        membershipPlans.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MEMBERSHIP PLANS");
        membershipPlans.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        navbar.add(membershipPlans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 40));

        jPanel1.add(navbar);
        navbar.setBounds(0, 0, 170, 470);

        header.setBackground(new java.awt.Color(0, 0, 0));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashlogout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dashlogout.setText("LOG OUT");
        dashlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashlogoutActionPerformed(evt);
            }
        });
        header.add(dashlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 100, 40));

        jPanel1.add(header);
        header.setBounds(170, 0, 740, 60);

        maindesktop.setBackground(new java.awt.Color(153, 153, 153));
        maindesktop.setPreferredSize(new java.awt.Dimension(760, 420));

        javax.swing.GroupLayout maindesktopLayout = new javax.swing.GroupLayout(maindesktop);
        maindesktop.setLayout(maindesktopLayout);
        maindesktopLayout.setHorizontalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        maindesktopLayout.setVerticalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jPanel1.add(maindesktop);
        maindesktop.setBounds(170, 60, 740, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(925, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpaneMouseEntered
      dashpane.setBackground(bodycolor);
    }//GEN-LAST:event_dashpaneMouseEntered

    private void dashpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpaneMouseExited
      dashpane.setBackground(navcolor);
    }//GEN-LAST:event_dashpaneMouseExited

    private void accountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseEntered
       account.setBackground(bodycolor);
    }//GEN-LAST:event_accountMouseEntered

    private void accountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseExited
        account.setBackground(navcolor);
    }//GEN-LAST:event_accountMouseExited

    private void paymentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentsMouseEntered
       payments.setBackground(bodycolor);
    }//GEN-LAST:event_paymentsMouseEntered

    private void paymentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentsMouseExited
       payments.setBackground(navcolor);
    }//GEN-LAST:event_paymentsMouseExited

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
    userprofile up = new userprofile();
    maindesktop.add(up).setVisible(true);
    
    Session sess = Session.getInstance();
    
    // This fills the labels you see in image_bf27a8.png
    up.p_name.setText(sess.getName()); 
    up.p_id.setText("" + sess.getId()); 
    up.p_email.setText(sess.getEmail());
    }//GEN-LAST:event_accountMouseClicked

    private void dashlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashlogoutActionPerformed
     int a = javax.swing.JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Select", javax.swing.JOptionPane.YES_NO_OPTION); 
    if (a == 0) {
        landingpage lp = new landingpage();
        lp.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_dashlogoutActionPerformed

    private void dashpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpaneMouseClicked
    dashBoardPage dbp = new dashBoardPage();
    maindesktop.add(dbp).setVisible(true);
    }//GEN-LAST:event_dashpaneMouseClicked

    private void activeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeMouseClicked
    config.Session sess = config.Session.getInstance();
    
    if (sess.getType().equalsIgnoreCase("STAFf")) {
       
        javax.swing.JOptionPane.showMessageDialog(null, "This section is restricted to Admin use only, Please contact the ADMIN. ");
    } else {
        
        active act = new active();
        maindesktop.removeAll();
        maindesktop.add(act);
        act.setVisible(true);
    }
    }//GEN-LAST:event_activeMouseClicked

    private void activeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeMouseEntered
     active.setBackground(bodycolor);
    }//GEN-LAST:event_activeMouseEntered

    private void activeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeMouseExited
     active.setBackground(navcolor);
    }//GEN-LAST:event_activeMouseExited

    private void membershipPlansMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membershipPlansMouseEntered
       membershipPlans.setBackground(bodycolor);
    }//GEN-LAST:event_membershipPlansMouseEntered

    private void membershipPlansMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membershipPlansMouseExited
       membershipPlans.setBackground(navcolor);
    }//GEN-LAST:event_membershipPlansMouseExited

    private void paymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentsMouseClicked
     // 1. Create the instance of the internal frame
    Payments mp = new Payments(); 
    
    // 2. Use your new variable name: maindesktop
    maindesktop.removeAll(); 
    maindesktop.add(mp);
    
    // 3. Make the internal frame visible inside the desktop
    mp.setVisible(true);
    
    // 4. Refresh the UI so the page appears immediately
    maindesktop.revalidate();
    maindesktop.repaint();
    }//GEN-LAST:event_paymentsMouseClicked

    private void membershipPlansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membershipPlansMouseClicked
   config.Session sess = config.Session.getInstance();
    
    if (sess.getType().equalsIgnoreCase("STAFf")) {
        javax.swing.JOptionPane.showMessageDialog(null, "This section is restricted to Admin use only.");
    } else {
        // Use the Class name 'membershipPlansForm', NOT the panel variable name
        internalPages.membershipPlansForm mem = new internalPages.membershipPlansForm(); 
        maindesktop.removeAll();
        maindesktop.add(mem);
        mem.setVisible(true);
        maindesktop.revalidate();
        maindesktop.repaint();
    }
    }//GEN-LAST:event_membershipPlansMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel account;
    private javax.swing.JPanel active;
    private javax.swing.JButton dashlogout;
    private javax.swing.JPanel dashpane;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JDesktopPane maindesktop;
    private javax.swing.JPanel membershipPlans;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel payments;
    // End of variables declaration//GEN-END:variables
}
